import { KoliBri } from '@public-ui/schema';

export const DEMO = KoliBri.createTheme('demo', {
    GLOBAL: `* { outline: 1px dotted purple !important; }`,
    // 'KOL-ABBR': abbrCss,
    // 'KOL-ACCORDION': accordionCss,
    // 'KOL-ALERT': alertCss,
    // 'KOL-BADGE': badgeCss,
    // 'KOL-BREADCRUMB': breadcrumbCss,
    // 'KOL-BUTTON': buttonCss,
    // 'KOL-BUTTON-GROUP': buttonGroupCss,
    // 'KOL-BUTTON-LINK': buttonLinkCss,
    // 'KOL-CARD': cardCss,
    // 'KOL-DETAILS': detailsCss,
    // 'KOL-HEADING': headingCss,
    // 'KOL-ICON': iconCss,
    // 'KOL-INDENTED-TEXT': indentedTextCss,
    // 'KOL-INPUT-CHECKBOX': inputCheckboxCss,
    // 'KOL-INPUT-COLOR': inputColorCss,
    // 'KOL-INPUT-DATE': inputDateCss,
    // 'KOL-INPUT-EMAIL': inputEmailCss,
    // 'KOL-INPUT-FILE': inputFileCss,
    // 'KOL-INPUT-NUMBER': inputNumberCss,
    // 'KOL-INPUT-PASSWORD': inputPasswordCss,
    // 'KOL-INPUT-RADIO': inputRadioCss,
    // 'KOL-INPUT-RANGE': inputRangeCss,
    // 'KOL-INPUT-TEXT': inputTextCss,
    // 'KOL-LINK': linkCss,
    // 'KOL-LINK-BUTTON': linkButtonCss,
    // 'KOL-MODAL': modalCss,
    // 'KOL-NAV': navCss,
    // 'KOL-PAGINATION': paginationCss,
    // 'KOL-PROGRESS': progressCss,
    // 'KOL-SELECT': selectCss,
    // 'KOL-SKIP-NAV': skipNavCss,
    // 'KOL-SPLIT-BUTTON': splitButtonCss,
    // 'KOL-TABLE': tableCss,
    // 'KOL-TABS': tabsCss,
    // 'KOL-TEXTAREA': textareaCss,
    // 'KOL-TOAST-CONTAINER': toastContainerCss,
    // 'KOL-TREE': treeCss,
    // 'KOL-TREE-ITEM': treeItemCss,
});
